{application,control,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{control_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[cmn_appl,control,control_app,control_sup,
                        orchestrate_control,orchestrate_lib,ssh_controller,
                        vm_appl_control]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
